[package]
name = "nyx-kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
# BOOTLOADER
bootloader_api = "0.11"
bootloader-boot-config = "0.11"

# ARCH
x86_64 = "0.14.13"

# HARDWARE
volatile = "0.2.6"
spin = "0.9.2"
uart_16550 = "0.2.19"
pc-keyboard = "0.7.0"
pic8259 = "0.10.1"
linked_list_allocator = "0.9.0"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }

# DATA
serde = { version = "1.0.197", default-features = false, features = ["derive", "alloc"] }
log = { version = "0.4", default-features = false }

# GRAPHICS (Updated to enable 32px font)
noto-sans-mono-bitmap = { version = "0.2.0", features = ["size_32"] }

[package.metadata.bootloader]
run-args = ["-display", "none", "-serial", "stdio"]